"""Incident model representing reported or detected safety incidents."""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Float, DateTime, Text, ForeignKey, Integer
from sqlalchemy.orm import relationship
from backend.app.database import Base


class Incident(Base):
    __tablename__ = "incidents"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    case_id = Column(String(36), ForeignKey("cases.id"), nullable=True, index=True)
    user_id = Column(String(36), ForeignKey("users.id"), nullable=True, index=True)
    
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    area_name = Column(String(255), nullable=False)  # e.g., "Patia Infocity", "Master Canteen"
    category = Column(String(100), nullable=False)  # "Harassment", "Stalking", "Suspicious Activity", "Theft", "Assault"
    severity = Column(String(50), nullable=False, default="MEDIUM")  # LOW, MEDIUM, HIGH, CRITICAL
    
    # Raw narrative (Private to User, never directly exposed to Authority)
    raw_narrative = Column(Text, nullable=False)
    
    # Sanitized narrative (Generated by Privacy-Guardian)
    sanitized_narrative = Column(Text, nullable=True)
    
    # Offender / Perpetrator description (used for vector matching)
    perpetrator_description = Column(Text, nullable=True)
    
    lighting_condition = Column(String(50), default="POOR")  # GOOD, MODERATE, POOR, DARK
    crowd_density = Column(String(50), default="ISOLATED")  # DENSE, MODERATE, SPARSE, ISOLATED
    status = Column(String(50), default="REPORTED")  # REPORTED, ESCALATED, INVESTIGATING, RESOLVED
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    case = relationship("Case", back_populates="incidents")
