"""Flagged Risk Zones Seed Data for Bhubaneswar."""

from typing import List, Dict, Any

MOCK_RISK_ZONES: List[Dict[str, Any]] = [
    {
        "zone_code": "ZONE-PATIA-01",
        "name": "Infocity Dark Forest Edge & Back Corridor",
        "description": "Unlit secondary lane connecting Infocity software park with outer forest edge. Non-functional sodium streetlights and dense blind corners.",
        "latitude": 20.3550,
        "longitude": 85.8180,
        "radius_meters": 180.0,
        "base_threat_level": "CRITICAL",
        "lighting_rating": 1.5,
        "patrol_frequency": "RARE",
        "offender_count": 2,
        "historical_incident_count": 8,
    },
    {
        "zone_code": "ZONE-SAILASHREE-02",
        "name": "Sailashree Vihar Unlit Footpath Loop",
        "description": "Isolated residential boundary corridor with sparse pedestrian traffic after 9:00 PM.",
        "latitude": 20.3380,
        "longitude": 85.8120,
        "radius_meters": 160.0,
        "base_threat_level": "HIGH",
        "lighting_rating": 1.8,
        "patrol_frequency": "RARE",
        "offender_count": 1,
        "historical_incident_count": 5,
    },
    {
        "zone_code": "ZONE-VANI-03",
        "name": "Vani Vihar Dark Botanical Perimeter",
        "description": "Heavily foliaged unmonitored road along university rear wall. Frequent stalking and harassment reports.",
        "latitude": 20.3010,
        "longitude": 85.8420,
        "radius_meters": 170.0,
        "base_threat_level": "HIGH",
        "lighting_rating": 2.0,
        "patrol_frequency": "RARE",
        "offender_count": 1,
        "historical_incident_count": 6,
    },
    {
        "zone_code": "ZONE-STATION-04",
        "name": "Station Back-Alley & Parcel Cargo Yard",
        "description": "Blind alleys between railway platform exits and cargo depot. Broken CCTV coverage and high transient loitering.",
        "latitude": 20.2640,
        "longitude": 85.8460,
        "radius_meters": 200.0,
        "base_threat_level": "CRITICAL",
        "lighting_rating": 2.1,
        "patrol_frequency": "OCCASIONAL",
        "offender_count": 2,
        "historical_incident_count": 9,
    },
    {
        "zone_code": "ZONE-JAGAMARA-05",
        "name": "Jagamara Hostel Back Lane & Drain Corridor",
        "description": "Unlit narrow lane behind student hostels near Khandagiri-Jagamara stretch. Poor drainage-side visibility, no CCTV, and frequent eve-teasing reports after dark.",
        "latitude": 20.2635,
        "longitude": 85.7870,
        "radius_meters": 150.0,
        "base_threat_level": "HIGH",
        "lighting_rating": 1.9,
        "patrol_frequency": "RARE",
        "offender_count": 1,
        "historical_incident_count": 4,
    },
]
